service: aws-serverless-dynamodb-sandbox

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:DEFAULT_AWS_REGION}
  stage: ${opt:stage}
  profile: aws-serverless-dynamodb-sandbox
custom:
  webpack:
    webpackConfig: config/webpack.config.js
    includeModules: false
    packager: yarn
  dynamodb:
    stages:
      - local
    start:
      port: ${env:LOCAL_DYNAMODB_PORT}
      inMemory: true
      migrate: true
      seed: true
      sharedDb: true
    seed:
      test:
        sources:
          - table: ${env:DB_TABLE_NAME_ITEMS}
            sources: [./src/database/itemsTableData.json]
functions:
  proxy:
    name: proxy
    memorySize: 256
    timeout: 120
    handler: src/index.index
    events:
      - http:
          path: /
          method: post
resources:
  Resources:
    WatchersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DB_TABLE_NAME_ITEMS}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
