service: aws-serverless-dynamodb-sandbox

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  profile: aws-serverless-dynamodb-sandbox
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'
  dynamodb:
    start:
      port: 3001
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      sharedDb: true
      noStart: false
    seed:
      test:
        sources:
          - table: itemsTable
            sources: [./src/itemsTableData.json]
functions:
  proxy:
    name: proxy
    memorySize: 256
    timeout: 120
    handler: src/index.index
    events:
      - http:
          path: /
          method: post
resources:
  Resources:
    WatchersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: itemsTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
